server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:certificate.p12
    key-store-password: Wen@pi0224$
    key-store-type: PKCS12
    key-alias: myalias

spring:
  application:
    name: ApplicationService
  mvc:
    pathmatch:
      matching-strategy: PathPatternParser

api:
  username: M.gabsi
  password: Mhgi0643$
  domain: WENGLER
  host: http://213.135.235.116:7048/BC140/api/beta/items
  base_url: http://213.135.235.116:7048/BC140/ODataV4/Company('Caves%20Wengler%20S.A.')
  base_url_beta: http://213.135.116:7048/BC140/api/beta/items
  resource:
    list_item: /Ecom_ItemList
    list_item_variant: /Ecom_ItemVariant
    list_attributs_variant: /Ecom_ItemAttribut
    category: /Ecom_CategoryList
    country: /Ecom_Country
    custom_path: /Ecom_CustomerList
    adressDeliveryPath: /Ecom_CustomerDeliveryAdress
    orderHeaderPath: /Ecom_SalesOrderHeader
    orderLinePath: /Ecom_SalesOrderLine
    list_compaign: /Ecom_Compaign
    list_compaign_detail: /Ecom_CampaignLine