server:
  port: 8080

spring:
  application:
    name: ApplicationService
  mvc:
    pathmatch:
      matching-strategy: PathPatternParser

api:
  username: M.gabsi
  password: Mhgi0643$
  domain: WENGLER
  base_url: http://213.135.235.116:5048/BC140_DEV/ODataV4/Company('Caves%20Wengler%20S.A.')
  base_url_beta: http://bc.wengler.lu:14058/BC140_Test/api/beta/items
  resource:
      list_item: /Ecom_ItemList
      list_item_variant: /Ecom_ItemVariant
      list_attributs_variant: /Ecom_ItemAttribut
      category: /Ecom_CategoryList
      country: /Ecom_Country
      custom_path: /Ecom_CustomerList
      adressDeliveryPath: /Ecom_CustomerDeliveryAdress