server:
  port: 9092

spring:
  application:
    name: ApplicationService
  mvc:
    pathmatch:
      matching-strategy: PathPatternParser

api:
  username: M.gabsi
  password: Mhgi0643$
  domain: WENGLER
  base_url: http://bc.wengler.lu:14058/BC140_Test/ODataV4/Company('Caves%20Wengler%20S.A.')
  resource:
      list_item: /Ecom_ItemList
      list_item_variant: /Ecom_ItemVariant
      list_attributs_variant: /Ecom_ItemAttribut
      category: /Ecom_CategoryList
      country: /Ecom_Country
      custom_path: /Ecom_CustomerList
      adressDeliveryPath: /Ecom_CustomerDeliveryAdress